### ISSUE TITLE
.env should not be under version control

### ISSUE THREAD

**Issue by scibuff** [nikakhachi/ts-express-template#1]
The `.env` file should never be under version control. The industry standard is to create a copy with dummy values, e.g. `.env.sample` or `.env.example` and commit that file

**Comment by nikakhachi** [comment]
Thanks for the suggestion. You are right.

I've added the labels and hopefully, someone can update it.

**Comment by JoePorterDev** [comment]
I can sort this out if you like :)

**Comment by nikakhachi** [comment]
@JoePorterDev Sure! That would be nice.

**Comment by JoePorterDev** [comment]
Quick question, are the values already dummy values? Or do these need changing?

**Comment by nikakhachi** [comment]
They are dummy values. You can leave them
